  linters:
    enable:
      - deadcode
      - dogsled
      - errcheck
      - funlen
      - goconst
      - gocyclo
      - gofmt
      - goimports
      - golint
      - gosec
      - gosimple
      - govet
      - ineffassign
      - interfacer
      - lll
      - maligned
      - misspell
      - staticcheck
      - structcheck
      - stylecheck
      - typecheck
      - unconvert
      - unparam
      - unused
      - varcheck
      - whitespace
  
  linters-settings:
    lll:
      line-length: 125
    maligned:
      suggest-new: true
    gocyclo:
      min-complexity: 11
    funlen:
      lines: 77
      statements: 50